config:
  imagesPath: "./img/characters/"
characters:
  game:
    name: ""
    color: white
  player:
    style:
      color: orange
    sprites:
      idle: none
    name: You
  marinette:
    sprites:
      idle: marinette_ladybug.png
      commie: marinette_commie.png
      cap: marinette_cappie.png
    style:
      color: white
    name: Marinette
  marx:
    sprites:
      idle: tiki_commie.png
    style:
      color: white
    name: Karl Marx
  adrian:
    sprites:
      idle: adriain_agreste.jpg
      evil: evil_adriain_agreste.jpg
    style:
      color: white
    name: Adrian
  alya:
    sprites:
      idle: alya.png
    style:
      color: white
    name: Alya
  Gabe:
    sprites:
      idle: cap_gabreil.jpg
    style:
      color: white
    name: Gabreil
