---
gameTitle: Communist Ladybug
saveFileName: Narrat Demo
dialogPanel:
  textSpeed: 30
  animateText: true
  timeBetweenLines: 100
  overlayMode: true
  rightOffset: 100
  bottomOffset: 50
  width: 475
  height: 680
  hideDuringTransition: false
  showAfterScriptEnd: false
  showOldChoices: false
  showChoiceOutcomes: true
  lockSeenChoices: false
  allowSpacebarInChoices: false
  clickToFinish: true

input:
  showPromptsOnGamepad: true
  showPromptsOnKeyboard: true
  showBottomLegend: true
graphics:
  allowFullscreen: true
layout:
  backgrounds:
    width: 1280
    height: 720
  dialogBottomPadding: 70
  mobileDialogHeightPercentage: 60
  verticalLayoutThreshold: 600
  portraits:
    width: 150
    height: 225
notifications:
  timeOnScreen: 1.5
  alsoPrintInDialogue: true
hudStats:
  money:
    icon: img/ui/money.webp
    name: Money
    startingValue: 500
    minValue: 0
saves:
  mode: manual
  slots: 10
  runOnReload: "test_label_reload"
  autosaveDisabledOnLabels:
    - test_no_autosave
  allowManualSave: true
  autosaveFeedback:
    enabled: true
    duration: 0.5
    text: saving...
    backgroundImage: "img/ui/autosave_spinner_background.png"
    foregroundImage: "img/ui/autosave_spinner.png"
menuButtons:
  new-game:
    text: Start a new adventure
