screens:
  default:
    background: img/backgrounds/default.webp
  basement:
    background: img/backgrounds/basement.jpg
  city:
    background: img/backgrounds/cappie_dirty_city.jpg
  fountain:
    background: img/backgrounds/fountain.jpg
  office:
    background: img/backgrounds/office.jpg
  protest:
    background: img/backgrounds/protest.jpg
